### ISSUE TITLE
Probe Panel

### ISSUE THREAD

**Issue by hekav** [qtquickvcp/QtQuickVcp#49]
Hello,

I'm not sure if this belongs to here, I just ask my questions.

Since I want to operate my cnc mill with Cetus I need some extensions. So I implemented this https://github.com/verser-git/probe_screen to Cetus.
![probe](https://cloud.githubusercontent.com/assets/12659936/13920837/42cbe376-ef75-11e5-9b11-6c7c60ea8483.png)

I also plan to implement a automatic tool-probe. 
Since this is a gladevcp application there is a lot of python code. I didn't find a way to run the non GUI part of that python code on my host. With porting the python code to qt i ran also into difficulties.

In an architectural sense, where is the best place to implement the python functionalities ? Are there any plans for some sort of API for porting gladevcp applications to QtQuickVcp.     

Regards
Helmut

**Comment by strahlex** [comment]
First of all: Great work, this looks very promising. 

This is a common problem when GUI and application logic has no been properly separated. The correct way to solve this problem is to move the Python application logic into a (HAL) component on the host. How much HAL does your code already contain? One solution would be to implement the probing code in a Python HAL component and to expose the interface to the GUI via a  HAL remote component.

Also possible is to run the Python code as second Machinetalk instance. pymachinetalk tries to map the linuxcnc and hal API to Machinetalk components. However, I guess a interface to trigger the probing functions is required. Unless you want to add your own Machinetalk service exposing the interface over HAL remote would work again.
